variables:
      OWNER: ontresearch
      GIT_SUBMODULE_STRATEGY: recursive
      IMAGENAME: "epi2melabs-notebook"
image: ${IMAGE}

stages:
    - build
    - publish

build-branch:
    stage: build
    only:
        - branches
    before_script:
        - apk add make bash git openssl py3-virtualenv python3
    script:
        - echo "Logging in to internal gitlab container registry";
        - echo ${CI_BUILD_TOKEN} | docker login --username gitlab-ci-token --password-stdin ${ONTREGISTRY};
        - UPSTREAM=dev PYTHON=python3 make ${IMAGENAME};
        - TAG=${ONTREGISTRY}/${CI_PROJECT_PATH}/${IMAGENAME}:${CI_COMMIT_REF_NAME};
        - echo "Pushing ${TAG}";
        - docker tag $OWNER/${IMAGENAME}:latest ${TAG};
        - docker push ${TAG};
        # on dev tag/push with commit hash also
        - if [[ ${CI_COMMIT_BRANCH} == 'dev' ]]; then
              DEVTAG=${TAG}-${CI_COMMIT_SHORT_SHA};
              echo "Pushing ${DEV_TAG}";
              docker tag $OWNER/${IMAGENAME}:latest ${DEVTAG};
              docker push ${DEVTAG};
              HUBTAG=ontresearch/${IMAGENAME}:dev;
              echo "Pushing dockerhub ${HUBTAG}";
              echo ${DOCKERHUB_TOKEN} | docker login --username epi2melabs --password-stdin;
              docker tag $OWNER/${IMAGENAME}:latest ${HUBTAG};
              docker push ${HUBTAG};
          fi
        - echo "All done";

publish-tag:
    stage: publish
    only:
        - tags
    before_script:
        - apk add make bash git openssl py3-virtualenv python3
    script:
        # We could pull the dev-commit tag from the repo, but instead let's
        # always build from the latest tag of the upstream image on dockerhub.
        # All being well this should amount to the same thing.
        - echo "Logging in to internal gitlab container registry";
        - echo ${DOCKERHUB_TOKEN} | docker login --username epi2melabs --password-stdin;
        - export UPSTREAM=$(make echo_latest_upstream | tail -n 1);
        - echo "Upstream tag ${UPSTREAM}";
        - PYTHON=python3 make ${IMAGENAME};
        - HUBTAG=ontresearch/${IMAGENAME}:${CI_COMMIT_TAG};
        - echo "Pushing dockerhub ${HUBTAG}";
        - docker tag $OWNER/${IMAGENAME}:latest ${HUBTAG};
        - docker push ${HUBTAG};
